[2025-09-25T05:12:38.533+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:12:38.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:12:38.537+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:12:38.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:12:38.542+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:12:38.541+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:12:38.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:12:38.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.045 seconds
[2025-09-25T05:13:09.105+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:13:09.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:13:09.108+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:13:09.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:13:09.111+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:13:09.110+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:13:09.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:13:09.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.027 seconds
[2025-09-25T05:13:39.553+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:13:39.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:13:39.556+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:13:39.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:13:39.559+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:13:39.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:13:39.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:13:39.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
[2025-09-25T05:14:10.477+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:14:10.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:14:10.480+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:14:10.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:14:10.484+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:14:10.483+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:14:10.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:14:10.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
[2025-09-25T05:14:40.664+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:14:40.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:14:40.667+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:14:40.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:14:40.672+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:14:40.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:14:40.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:14:40.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.034 seconds
[2025-09-25T05:15:10.836+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:15:10.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:15:10.839+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:15:10.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:15:10.842+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:15:10.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:15:10.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:15:10.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.033 seconds
[2025-09-25T05:15:41.293+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:15:41.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:15:41.297+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:15:41.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:15:41.301+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:15:41.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:15:41.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:15:41.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.037 seconds
[2025-09-25T05:16:11.616+0000] {processor.py:186} INFO - Started process (PID=512) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:16:11.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:16:11.621+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:16:11.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:16:11.624+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:16:11.623+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:16:11.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:16:11.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.032 seconds
[2025-09-25T05:16:42.186+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:16:42.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:16:42.191+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:16:42.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:16:42.194+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:16:42.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:16:42.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:16:42.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.031 seconds
[2025-09-25T05:17:12.370+0000] {processor.py:186} INFO - Started process (PID=642) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:17:12.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:17:12.374+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:17:12.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:17:12.377+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:17:12.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:17:12.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:17:12.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.032 seconds
[2025-09-25T05:17:42.550+0000] {processor.py:186} INFO - Started process (PID=707) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:17:42.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:17:42.553+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:17:42.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:17:42.557+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:17:42.556+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:17:42.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:17:42.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.031 seconds
[2025-09-25T05:18:13.091+0000] {processor.py:186} INFO - Started process (PID=772) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:18:13.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:18:13.095+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:18:13.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:18:13.098+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:18:13.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:18:13.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:18:13.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.033 seconds
[2025-09-25T05:18:43.452+0000] {processor.py:186} INFO - Started process (PID=837) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:18:43.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:18:43.457+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:18:43.456+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:18:43.460+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:18:43.459+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:18:43.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:18:43.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.032 seconds
[2025-09-25T05:19:13.647+0000] {processor.py:186} INFO - Started process (PID=902) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:19:13.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:19:13.651+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:19:13.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:19:13.654+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:19:13.653+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:19:13.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:19:13.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.030 seconds
[2025-09-25T05:19:43.775+0000] {processor.py:186} INFO - Started process (PID=967) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:19:43.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:19:43.780+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:19:43.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:19:43.783+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:19:43.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:19:43.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:19:43.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.031 seconds
[2025-09-25T05:25:39.234+0000] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:25:39.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:25:39.244+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:25:39.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:25:39.250+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:25:39.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:25:39.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:25:39.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.047 seconds
[2025-09-25T05:26:09.365+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:26:09.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:26:09.369+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:26:09.368+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:26:09.372+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:26:09.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:26:09.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:26:09.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.033 seconds
[2025-09-25T05:26:40.026+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:26:40.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:26:40.032+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:26:40.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:26:40.039+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:26:40.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:26:40.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:26:40.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.046 seconds
[2025-09-25T05:27:10.165+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:27:10.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:27:10.168+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:27:10.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:27:10.172+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:27:10.171+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:27:10.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:27:10.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:27:40.340+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:27:40.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:27:40.343+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:27:40.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:27:40.346+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:27:40.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:27:40.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:27:40.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:28:53.467+0000] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:28:53.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:28:53.474+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:28:53.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:28:53.478+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:28:53.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:28:53.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:28:53.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.041 seconds
[2025-09-25T05:29:23.637+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:29:23.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:29:23.642+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:29:23.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:29:23.645+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:29:23.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:29:23.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:29:23.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:29:53.885+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:29:53.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:29:53.888+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:29:53.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:29:53.891+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:29:53.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:29:53.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:29:53.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.030 seconds
[2025-09-25T05:30:24.257+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:30:24.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:30:24.260+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:30:24.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:30:24.263+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:30:24.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:30:24.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:30:24.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.033 seconds
[2025-09-25T05:30:54.935+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:30:54.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:30:54.938+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:30:54.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:30:54.941+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:30:54.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:30:54.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:30:54.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.027 seconds
[2025-09-25T05:31:25.141+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:31:25.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:31:25.144+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:31:25.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:31:25.147+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:31:25.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:31:25.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:31:25.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:31:55.283+0000] {processor.py:186} INFO - Started process (PID=448) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:31:55.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:31:55.287+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:31:55.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:31:55.291+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:31:55.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:31:55.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:31:55.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.032 seconds
[2025-09-25T05:32:25.572+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:32:25.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:32:25.575+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:32:25.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:32:25.579+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:32:25.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:32:25.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:32:25.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.031 seconds
[2025-09-25T05:32:56.076+0000] {processor.py:186} INFO - Started process (PID=578) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:32:56.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:32:56.081+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:32:56.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:32:56.083+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:32:56.083+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:32:56.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:32:56.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.026 seconds
[2025-09-25T05:33:26.157+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:33:26.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:33:26.162+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:33:26.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:33:26.166+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:33:26.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:33:26.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:33:26.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.035 seconds
[2025-09-25T05:33:56.380+0000] {processor.py:186} INFO - Started process (PID=708) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:33:56.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:33:56.384+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:33:56.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:33:56.388+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:33:56.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:33:56.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:33:56.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.036 seconds
[2025-09-25T05:34:26.607+0000] {processor.py:186} INFO - Started process (PID=773) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:34:26.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:34:26.612+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:34:26.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:34:26.615+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:34:26.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:34:26.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:34:26.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:34:56.856+0000] {processor.py:186} INFO - Started process (PID=838) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:34:56.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:34:56.859+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:34:56.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:34:56.862+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:34:56.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:34:56.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:34:56.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
[2025-09-25T05:35:27.166+0000] {processor.py:186} INFO - Started process (PID=903) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:35:27.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:35:27.171+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:35:27.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:35:27.174+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:35:27.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:35:27.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:35:27.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.030 seconds
[2025-09-25T05:35:57.590+0000] {processor.py:186} INFO - Started process (PID=968) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:35:57.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:35:57.593+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:35:57.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:35:57.596+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:35:57.595+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:35:57.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:35:57.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
[2025-09-25T05:36:27.990+0000] {processor.py:186} INFO - Started process (PID=1033) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:36:27.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:36:27.994+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:36:27.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:36:27.998+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:36:27.997+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:36:27.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:36:28.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.032 seconds
[2025-09-25T05:36:58.570+0000] {processor.py:186} INFO - Started process (PID=1098) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:36:58.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:36:58.573+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:36:58.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:36:58.577+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:36:58.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:36:58.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:36:58.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
[2025-09-25T05:37:28.870+0000] {processor.py:186} INFO - Started process (PID=1163) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:37:28.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:37:28.874+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:37:28.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:37:28.877+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:37:28.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:37:28.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:37:28.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:37:59.284+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:37:59.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:37:59.287+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:37:59.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:37:59.290+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:37:59.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:37:59.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:37:59.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.031 seconds
[2025-09-25T05:38:29.534+0000] {processor.py:186} INFO - Started process (PID=1293) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:38:29.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:38:29.539+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:38:29.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:38:29.542+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:38:29.541+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:38:29.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:38:29.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.033 seconds
[2025-09-25T05:38:59.934+0000] {processor.py:186} INFO - Started process (PID=1358) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:38:59.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:38:59.939+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:38:59.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:38:59.942+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:38:59.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:38:59.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:38:59.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:39:30.647+0000] {processor.py:186} INFO - Started process (PID=1423) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:39:30.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:39:30.652+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:39:30.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:39:30.656+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:39:30.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:39:30.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:39:30.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.032 seconds
[2025-09-25T05:40:00.768+0000] {processor.py:186} INFO - Started process (PID=1488) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:40:00.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:40:00.771+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:40:00.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:40:00.774+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:40:00.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:40:00.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:40:00.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:40:31.054+0000] {processor.py:186} INFO - Started process (PID=1553) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:40:31.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:40:31.060+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:40:31.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:40:31.063+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:40:31.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:40:31.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:40:31.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.031 seconds
[2025-09-25T05:41:01.394+0000] {processor.py:186} INFO - Started process (PID=1618) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:41:01.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:41:01.398+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:41:01.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:41:01.400+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:41:01.399+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:41:01.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:41:01.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.027 seconds
[2025-09-25T05:41:31.789+0000] {processor.py:186} INFO - Started process (PID=1683) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:41:31.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:41:31.800+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:41:31.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:41:31.804+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:41:31.803+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:41:31.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:41:31.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.043 seconds
[2025-09-25T05:42:02.354+0000] {processor.py:186} INFO - Started process (PID=1748) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:42:02.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:42:02.359+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:42:02.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:42:02.363+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:42:02.362+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:42:02.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:42:02.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.033 seconds
[2025-09-25T05:42:32.584+0000] {processor.py:186} INFO - Started process (PID=1813) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:42:32.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:42:32.587+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:42:32.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:42:32.590+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:42:32.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:42:32.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:42:32.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
[2025-09-25T05:43:02.821+0000] {processor.py:186} INFO - Started process (PID=1878) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:43:02.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:43:02.824+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:43:02.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:43:02.827+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:43:02.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:43:02.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:43:02.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.027 seconds
[2025-09-25T05:43:33.482+0000] {processor.py:186} INFO - Started process (PID=1943) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:43:33.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:43:33.485+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:43:33.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:43:33.488+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:43:33.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:43:33.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:43:33.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.029 seconds
[2025-09-25T05:44:03.776+0000] {processor.py:186} INFO - Started process (PID=2008) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:44:03.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:44:03.781+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:44:03.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:44:03.784+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:44:03.783+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:44:03.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:44:03.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
[2025-09-25T05:44:34.477+0000] {processor.py:186} INFO - Started process (PID=2073) to work on /opt/airflow/dags/my_dag.py
[2025-09-25T05:44:34.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2025-09-25T05:44:34.480+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:44:34.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2025-09-25T05:44:34.483+0000] {logging_mixin.py:190} INFO - [2025-09-25T05:44:34.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-09-25T05:44:34.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2025-09-25T05:44:34.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
