[2025-09-24T18:44:12.285+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_dag.insert_test_user manual__2025-09-24T18:44:07.960057+00:00 [queued]>
[2025-09-24T18:44:12.290+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_dag.insert_test_user manual__2025-09-24T18:44:07.960057+00:00 [queued]>
[2025-09-24T18:44:12.291+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-24T18:44:12.299+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): insert_test_user> on 2025-09-24 18:44:07.960057+00:00
[2025-09-24T18:44:12.303+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2025-09-24T18:44:12.306+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_postgres_dag', 'insert_test_user', 'manual__2025-09-24T18:44:07.960057+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpq76gqx6g']
[2025-09-24T18:44:12.308+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask insert_test_user
[2025-09-24T18:44:12.342+0000] {task_command.py:423} INFO - Running <TaskInstance: test_postgres_dag.insert_test_user manual__2025-09-24T18:44:07.960057+00:00 [running]> on host d59ad7cc807c
[2025-09-24T18:44:12.392+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_postgres_dag' AIRFLOW_CTX_TASK_ID='insert_test_user' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T18:44:07.960057+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-24T18:44:07.960057+00:00'
[2025-09-24T18:44:12.394+0000] {sql.py:276} INFO - Executing: 
            INSERT INTO public.users (firstname, lastname, country, username, password, email)
            VALUES ('Bruce', 'Wayne', 'USA', 'batman', 'darkknight', 'bruce@wayne.com');
        
[2025-09-24T18:44:12.400+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2025-09-24T18:44:12.408+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2025-09-24T18:44:12.412+0000] {sql.py:450} INFO - Running statement: 
            INSERT INTO public.users (firstname, lastname, country, username, password, email)
            VALUES ('Bruce', 'Wayne', 'USA', 'batman', 'darkknight', 'bruce@wayne.com');
        , parameters: None
[2025-09-24T18:44:12.413+0000] {sql.py:459} INFO - Rows affected: 1
[2025-09-24T18:44:12.420+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_postgres_dag, task_id=insert_test_user, execution_date=20250924T184407, start_date=20250924T184412, end_date=20250924T184412
[2025-09-24T18:44:12.438+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-24T18:44:12.453+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
